if(__install_dependencies)
	return()
endif()
set(__install_dependencies YES)

macro(install_dll depdir dllname)
	foreach(configuration ${CMAKE_CONFIGURATION_TYPES})
		set(dllpath "${depdir}/bin/${configuration}/${dllname}")
		if(EXISTS ${dllpath})
			install(FILES ${dllpath} DESTINATION bin/${configuration} CONFIGURATIONS ${configuration})
		endif()
	endforeach()
endmacro()

macro(copy_dll depdir dllname)
	foreach(configuration ${CMAKE_CONFIGURATION_TYPES})
		set(dllpath "${depdir}/bin/${configuration}/${dllname}")
		if(EXISTS ${dllpath})
			configure_file(${dllpath} ${CMAKE_BINARY_DIR}/bin/${configuration}/${dllname} COPYONLY)
		endif()
	endforeach()
endmacro()

# PIL
set(PIL_DLL_NAME "platform.dll")
set(PIL_DIR "${CMAKE_SOURCE_DIR}/Deps/platform/win32/PIL")
if(EXISTS ${PIL_DIR})
	message("Found PIL in ${PIL_DIR}")
	copy_dll(${PIL_DIR} ${PIL_DLL_NAME})
	install_dll(${PIL_DIR} ${PIL_DLL_NAME})
else()
	message("Not found PIL")
endif()